config/routes.rb
Onholiday::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  resource :vacation_request
  get "annual_leaves", to: "vacation_requests#index", as: "vacation_requests"


  get "/timetable", to: "work_hours#index", as: "timetable"
  get "/stats", to: "statistics#index", as: "stats"

  post "/working_hour/add/:user_id/:day/:hour", to: "work_hours#add"
  post "/working_hour/remove/:user_id/:day/:hour", to: "work_hours#remove"


  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users

  end

end

app/models/vacation_request.rb
class VacationRequest < ActiveRecord::Base
  validates :user, presence: true
  belongs_to :user
end

app/controllers/vacation_requests_controller.rb
class VacationRequestsController < ApplicationController
  before_action :authenticate_user!


    def index
      @new_vacation_request =  current_user.vacation_requests.new
      @vacation_requests = VacationRequest.all
    end

    def create
      @vacation_request = VacationRequest.create(vacation_request_params)
      if @vacation_request.save
        flash[:notice] = "Successfully requested a annual leave"
        redirect_to vacation_requests_path
      else
        flash[:warning] = "Could not request annual leave"
        redirect_to vacation_requests_path
      end
    end

    def destroy
      @vacation_request = VacationRequest.find(params[:id])
      @vacation_request.destroy

      redirect_to vacation_requests_path
    end

    def vacation_request_params
      params.require(:vacation_request).permit(:start,:end,:reason, :user_id)
    end
end

app/views/vacation_requests/_form.html.erb
<div class="row">

  <%= form_for(@new_vacation_request, url: vacation_request_path) do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="form-group">
      <h4>Request Annual Leave:</h4>
      <hr>
    <div class="row">
      <div class="col-sm-3">
        <%= f.label :start %><br>
        <%= f.date_field :start, class: "form-control" %>
      </div>
      <div class="col-sm-3">
        <%= f.label :end %>
        <%= f.date_field :end, class: "form-control" %>
      </div>
      <div class="col-sm-6">
        <%= f.label :reason %>
        <%= f.text_field :reason, class: "form-control", placeholder: "Optional" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= f.submit "Request", class: "btn btn-primary" %>
    </div>
  </div>

  <% end %>
</div>

app/views/vacation_requests/_index.html.erb
<div class="row">
  <div class="col-md-12">
    <h4>Annual Leave Requests:</h4>
    <hr>
  </div>
  <div class="col-md-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Start</th>
          <th>End</th>
          <th>Reason</th>
          <th>Requester</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @vacation_requests.each do |request| %>
          <tr>
            <td><%= request.start %></td>
            <td><%= request.end %></td>
            <td><%= request.reason %></td>
            <td><%= "#{request.user.try(:first_name)} #{request.user.try(:last_name)}" %></td>
            <td>
              <% if current_user.admin? || current_user == request.user %>
                <%= link_to "Remove", vacation_request_path(request), method: :delete , class: "btn btn-sm btn-warning" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/vacation_requests/index.html.erb
<% unless current_user.admin? %>
  <%= render  "form" %>
<% end %>


<div class="row">
<%= render "index" %>
</div>